### ISSUE TITLE
[olea/2017-geocamp] Page build warning

### ISSUE THREAD

**Issue by olea** [olea/2017-geocamp#4]
Mensaje automático desde GitHub <support@github.com>

>  The page build completed successfully, but returned the following warning for the `gh-pages` branch:
>
> Your site's DNS settings are using a custom subdomain, 2017.geocamp.es, that's set up as an A record. We recommend you change this to a CNAME record pointing at olea.github.io. For more information, see https://help.github.com/pages/.
>
> For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds
>
>If you have any questions you can contact us by replying to this email.

**Comment by jsanz** [comment]
como hemos movido el repo a otra organización esto ya no aplica
